version: '3.7'

services:
  nginx:
    image: nginx
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./nginx:/etc/nginx/nginx.conf.d
    depends_on:
      - api
    restart: "on-failure"
  api:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    links:
        - db
    environment:
      MONGODB_URI: mongodb://db:27017/songs_db
      MONGODB_DBNAME: ${MONGODB_DBNAME}
    command: /dev.sh
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
  db:
      image: mongo:4.4
      environment:
        MONGODB_DBNAME: ${MONGODB_DBNAME}
      ports:
        - "27017:27017"