version: 2.1

orbs:
  python: circleci/python1.2
  coveralls: coveralls/coveralls@3.2.0

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          name: Run Tests
          command: coverage run -m pytest -vv && coveralls


workflows:
  main:
    jobs:
      - build-and-test
