version: 2.1

orbs:
  python: circleci/python@0.2.1
  coveralls: coveralls/coveralls@1.0.6

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
      - image: circleci/mongo:4.4
        environment:
          MONGODB_URI: mongodb://127.0.0.1:27017/songs_db
          MONGODB_DBNAME: ${MONGODB_DBNAME}
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          name: Run Tests
          command: coverage run -m pytest -vv && coveralls


workflows:
  main:
    jobs:
      - build-and-test
